
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Initialize data

```{r warning=FALSE}
if (!file.exists("2010_sqf_m35.csv")) {
  download.file("http://math.hmc.edu/m35f/2010_sqf_m35.csv", "2010_sqf_m35.csv")
}
if (!file.exists("2015_sqf_m35.csv")) {
  download.file("http://math.hmc.edu/m35f/2015_sqf_m35.csv", "2015_sqf_m35.csv")
}
sqf2010 <- read.csv("2010_sqf_m35.csv")
sqf2015 <- read.csv("2015_sqf_m35.csv")
sqf2015 <- sqf2015[!sqf2015$perstop == "*" && !sqf2015$perstop == " ",]
sqf2015$perstop <- as.numeric(as.character(sqf2015$perstop))
```

## Set helper functions

```{r}
make_ci <- function(xs, alpha) {
  xs_mean <- mean(xs)
  xs_sd <- sd(xs)
  xs_n <- length(xs)
  xs_t <- abs( qt(alpha/2, xs_n - 1) )
  xs_me <- xs_t * xs_sd / sqrt(xs_n)
  return(c(xs_mean - xs_me, xs_mean + xs_me))
}

print_ci <- function(name, ci) {
  print(c(name, ci[1], ci[2]))
}
```

## Print confidence intervals

```{r}
# entire sample
print_ci("entire sample", make_ci(sqf2015$perobs, 0.05))

# each race
for (r in levels(sqf2015$race)) {
  race_subset <- subset(sqf2015, sqf2015$race == r)
  print_ci(r, make_ci(race_subset$perobs, 0.05))
}
```
