
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Initialize data

```{r warning=FALSE}
if (!file.exists("2010_sqf_m35.csv")) {
  download.file("http://math.hmc.edu/m35f/2010_sqf_m35.csv", "2010_sqf_m35.csv")
}
if (!file.exists("2015_sqf_m35.csv")) {
  download.file("http://math.hmc.edu/m35f/2015_sqf_m35.csv", "2015_sqf_m35.csv")
}
sqf2010 <- read.csv("2010_sqf_m35.csv")
sqf2015 <- read.csv("2015_sqf_m35.csv")
sqf2015 <- sqf2015[!sqf2015$perstop == "*" && !sqf2015$perstop == " ",]
sqf2015$perstop <- as.numeric(as.character(sqf2015$perstop))
```

## Remove extraneous values and subset

```{r}
sqf2015.clean <- subset(sqf2015, 0 < age & age < 100)
sqf2015.male <- subset(sqf2015.clean, sex == "M")
sqf2015.female <- subset(sqf2015.clean, sex == "F")
```

The data was filtered for age between 0 and 100, exclusive. Furthermore, male and female sexes were subsetted.

## Plot

```{r}
par(mfrow=c(1, 2))

qqnorm(sqf2015.male$age, main = "Q-Q Plot - Age of males")
qqline(sqf2015.male$age)

qqnorm(sqf2015.female$age, main = "Q-Q Plot - Age of females")
qqline(sqf2015.female$age)
```

We observe that age of males and females are skewed right are heavy tailed. The age of males seems to have more values clustered at the extremes 0 and 100 years.